# Generated by Django 5.0.7 on 2024-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vegitables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('buyer', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phoneno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
