# Generated by Django 5.0.7 on 2024-07-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0002_alter_vegitables_phoneno_alter_vegitables_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegitables',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vegitables',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='vegitables',
            name='phoneno',
        ),
    ]
