# Generated by Django 5.0.7 on 2024-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0006_customer_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
