# Generated by Django 5.0.7 on 2024-07-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0007_alter_customer_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
