# Generated by Django 5.0.7 on 2024-07-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0009_alter_customer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegitables',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
